version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://host.docker.internal:4000
